/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mastermind_b_k;

import java.awt.Button;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author ilonabematol
 */
public class fenetre_de_jeu extends javax.swing.JFrame {

    /**
     * Creates new form fenetre_de_jeu
     */
    Grille_principale obj1 = new Grille_principale();
    ArrayList<Integer> Indice = new ArrayList<>();
    ArrayList<String> Jeu_Joueur = new ArrayList<String>();
    int Pions;
    int compteurcoul;
    int ligne;
    int colonne;
    int ind;
    int emplacement;
    JButton jButton;
    CelluleGraphique obj2 = new CelluleGraphique(Pions);
    
    //Grille_principale grille= new Grille_principale() ;

    public fenetre_de_jeu() {
        initComponents();
        compteurcoul = 0;
        ind = -1;
        ligne = -1;
        rappel.setVisible(false);
        pannel_couleurs.setVisible(false);
        panneau_affichage.setVisible(false);

        
        for (int i = 0; i < 48; i++) {
            Jeu_Joueur.add(null);
            CelluleGraphique cellGraph = new CelluleGraphique(obj1.Indice.get(i));
            grilleAnalyse.add(obj2);
            grilleAnalyse.repaint();

        }
        /*
          Classe fenetre de jeu 
public void indice(){
      ligneEncours();
      
      obj1.analyse_Jeu_Joueur(ligne);
      for (int i=0; i<4; i++){
          if (obj1.Indice.get(i)==1 ){
             grilleAnalyse.setIcon(i;img_black);
             grilleAnalyse.repaint();
          }  
        else if ( obj1.Indice.get(i)==0) {
            grilleAnalyse.setIcon(i;img_white);
            grilleAnalyse.repaint();
                     }  
             
                        
  }
    
     }
cellGraph.addActionListener(new java.awt.event.ActionListener() {

                public void actionPerformed(java.awt.event.ActionEvent evt) {

                    String c = cellGraph.Pions;
                    if (c == null) {
                        Jeu_Joueur.set(avanc(),"Attente de couleur");
                        annonce.setText("Séléctionnez une couleur");
                        //Jeu_Joueur.set(i,"Attente de couleur");
                        System.out.println(Jeu_Joueur);
                        activeButton_coul();
            
                    }else{
                        switch (choixcoul(i)){
                           case 0: 
                               c.analyse_coul("R");
                           case  1 :
                               c.analyse_coul("P");
                           case 2 :
                               c.analyse_coul("G");
                           case 3:
                               c.analyse_coul("Y");
                           case 4:
                               c.analyse_coul("O");
                           case 5:
                               c.analyse_coul("B");
                        }
                    
                        
                    }
                      
                    
           }

            });
            
         */

    }

    /*public
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        grilleJeu = new javax.swing.JPanel();
        jButton_44 = new javax.swing.JButton();
        jButton_45 = new javax.swing.JButton();
        jButton_46 = new javax.swing.JButton();
        jButton_47 = new javax.swing.JButton();
        jButton_40 = new javax.swing.JButton();
        jButton_41 = new javax.swing.JButton();
        jButton_42 = new javax.swing.JButton();
        jButton_43 = new javax.swing.JButton();
        jButton_36 = new javax.swing.JButton();
        jButton_37 = new javax.swing.JButton();
        jButton_38 = new javax.swing.JButton();
        jButton_39 = new javax.swing.JButton();
        jButton_32 = new javax.swing.JButton();
        jButton_33 = new javax.swing.JButton();
        jButton_34 = new javax.swing.JButton();
        jButton_35 = new javax.swing.JButton();
        jButton_28 = new javax.swing.JButton();
        jButton_29 = new javax.swing.JButton();
        jButton_30 = new javax.swing.JButton();
        jButton_31 = new javax.swing.JButton();
        jButton_24 = new javax.swing.JButton();
        jButton_25 = new javax.swing.JButton();
        jButton_26 = new javax.swing.JButton();
        jButton_27 = new javax.swing.JButton();
        jButton_20 = new javax.swing.JButton();
        jButton_21 = new javax.swing.JButton();
        jButton_22 = new javax.swing.JButton();
        jButton_23 = new javax.swing.JButton();
        jButton_16 = new javax.swing.JButton();
        jButton_17 = new javax.swing.JButton();
        jButton_18 = new javax.swing.JButton();
        jButton_19 = new javax.swing.JButton();
        jButton_12 = new javax.swing.JButton();
        jButton_13 = new javax.swing.JButton();
        jButton_14 = new javax.swing.JButton();
        jButton_15 = new javax.swing.JButton();
        jButton_8 = new javax.swing.JButton();
        jButton_9 = new javax.swing.JButton();
        jButton_10 = new javax.swing.JButton();
        jButton_11 = new javax.swing.JButton();
        jButton_4 = new javax.swing.JButton();
        jButton_5 = new javax.swing.JButton();
        jButton_6 = new javax.swing.JButton();
        jButton_7 = new javax.swing.JButton();
        jButton_0 = new javax.swing.JButton();
        jButton_1 = new javax.swing.JButton();
        jButton_2 = new javax.swing.JButton();
        jButton_3 = new javax.swing.JButton();
        panneau_jeu = new javax.swing.JPanel();
        btn_start = new javax.swing.JButton();
        grilleAnalyse = new javax.swing.JPanel();
        panneau_affichage = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        annonce = new javax.swing.JTextArea();
        pannel_couleurs = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        col_red = new javax.swing.JButton();
        col_pink = new javax.swing.JButton();
        col_green = new javax.swing.JButton();
        col_yellow = new javax.swing.JButton();
        col_blue = new javax.swing.JButton();
        col_orange = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rappel = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grilleJeu.setBackground(new java.awt.Color(204, 204, 204));
        grilleJeu.setBorder(new javax.swing.border.MatteBorder(null));
        grilleJeu.setLayout(new java.awt.GridLayout(12, 4));

        jButton_44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_44ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_44);

        jButton_45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_45ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_45);

        jButton_46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_46ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_46);

        jButton_47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_47ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_47);

        jButton_40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_40ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_40);

        jButton_41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_41ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_41);

        jButton_42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_42ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_42);

        jButton_43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_43ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_43);

        jButton_36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_36ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_36);

        jButton_37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_37ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_37);

        jButton_38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_38ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_38);

        jButton_39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_39ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_39);

        jButton_32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_32ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_32);

        jButton_33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_33ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_33);

        jButton_34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_34ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_34);

        jButton_35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_35ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_35);

        jButton_28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_28ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_28);

        jButton_29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_29ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_29);

        jButton_30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_30ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_30);

        jButton_31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_31ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_31);

        jButton_24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_24ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_24);

        jButton_25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_25ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_25);

        jButton_26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_26ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_26);

        jButton_27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_27ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_27);

        jButton_20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_20ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_20);

        jButton_21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_21ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_21);

        jButton_22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_22ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_22);

        jButton_23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_23ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_23);

        jButton_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_16ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_16);

        jButton_17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_17ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_17);

        jButton_18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_18ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_18);

        jButton_19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_19ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_19);

        jButton_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_12ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_12);

        jButton_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_13ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_13);

        jButton_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_14ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_14);

        jButton_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_15ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_15);

        jButton_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_8ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_8);

        jButton_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_9ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_9);

        jButton_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_10ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_10);

        jButton_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_11ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_11);

        jButton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_4ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_4);

        jButton_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_5ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_5);

        jButton_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_6ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_6);

        jButton_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_7ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_7);

        jButton_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_0ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_0);

        jButton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_1);

        jButton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_2ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_2);

        jButton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_3ActionPerformed(evt);
            }
        });
        grilleJeu.add(jButton_3);

        getContentPane().add(grilleJeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 400, 600));

        panneau_jeu.setBackground(new java.awt.Color(255, 204, 204));

        btn_start.setText("Démarrer");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panneau_jeuLayout = new javax.swing.GroupLayout(panneau_jeu);
        panneau_jeu.setLayout(panneau_jeuLayout);
        panneau_jeuLayout.setHorizontalGroup(
            panneau_jeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneau_jeuLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btn_start, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        panneau_jeuLayout.setVerticalGroup(
            panneau_jeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_start, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        getContentPane().add(panneau_jeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 300, 50));

        grilleAnalyse.setBackground(new java.awt.Color(255, 204, 204));
        grilleAnalyse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        grilleAnalyse.setToolTipText("");
        grilleAnalyse.setLayout(new java.awt.GridLayout(24, 2));
        getContentPane().add(grilleAnalyse, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 150, 600));

        panneau_affichage.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel3.setText("GAME");

        annonce.setColumns(20);
        annonce.setFont(new java.awt.Font("Vampire Wars", 2, 12)); // NOI18N
        annonce.setForeground(new java.awt.Color(51, 51, 0));
        annonce.setLineWrap(true);
        annonce.setRows(2);
        jScrollPane1.setViewportView(annonce);

        javax.swing.GroupLayout panneau_affichageLayout = new javax.swing.GroupLayout(panneau_affichage);
        panneau_affichage.setLayout(panneau_affichageLayout);
        panneau_affichageLayout.setHorizontalGroup(
            panneau_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneau_affichageLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneau_affichageLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panneau_affichageLayout.setVerticalGroup(
            panneau_affichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneau_affichageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(panneau_affichage, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 300, 120));

        pannel_couleurs.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel2.setText("Choix couleurs");

        col_red.setBackground(new java.awt.Color(255, 0, 51));
        col_red.setFont(new java.awt.Font("Stencil", 0, 11)); // NOI18N
        col_red.setText("Rouge");
        col_red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col_redActionPerformed(evt);
            }
        });

        col_pink.setBackground(new java.awt.Color(255, 102, 255));
        col_pink.setFont(new java.awt.Font("Stencil", 0, 11)); // NOI18N
        col_pink.setText("Rose");
        col_pink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col_pinkActionPerformed(evt);
            }
        });

        col_green.setBackground(new java.awt.Color(0, 204, 51));
        col_green.setFont(new java.awt.Font("Stencil", 0, 11)); // NOI18N
        col_green.setText("Vert");
        col_green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col_greenActionPerformed(evt);
            }
        });

        col_yellow.setBackground(new java.awt.Color(255, 255, 51));
        col_yellow.setFont(new java.awt.Font("Stencil", 0, 11)); // NOI18N
        col_yellow.setText("Jaune");
        col_yellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col_yellowActionPerformed(evt);
            }
        });

        col_blue.setBackground(new java.awt.Color(102, 102, 255));
        col_blue.setFont(new java.awt.Font("Stencil", 0, 11)); // NOI18N
        col_blue.setText("Bleu");
        col_blue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col_blueActionPerformed(evt);
            }
        });

        col_orange.setBackground(new java.awt.Color(255, 153, 0));
        col_orange.setFont(new java.awt.Font("Stencil", 0, 11)); // NOI18N
        col_orange.setText("Orange");
        col_orange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                col_orangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pannel_couleursLayout = new javax.swing.GroupLayout(pannel_couleurs);
        pannel_couleurs.setLayout(pannel_couleursLayout);
        pannel_couleursLayout.setHorizontalGroup(
            pannel_couleursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannel_couleursLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pannel_couleursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(col_red, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(col_pink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(col_green, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pannel_couleursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(col_yellow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(col_orange, javax.swing.GroupLayout.PREFERRED_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(col_blue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannel_couleursLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(68, 68, 68))
        );
        pannel_couleursLayout.setVerticalGroup(
            pannel_couleursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannel_couleursLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(pannel_couleursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(col_red)
                    .addComponent(col_yellow))
                .addGap(36, 36, 36)
                .addGroup(pannel_couleursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(col_green)
                    .addComponent(col_blue))
                .addGap(38, 38, 38)
                .addGroup(pannel_couleursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(col_pink)
                    .addComponent(col_orange))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pannel_couleurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 300, 240));

        jLabel4.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        jLabel4.setText("MASTERMIND");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 200, 30));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Yu Gothic", 0, 11)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("CASE NOIRE : \n \tvous avez une bonne couleur \nCASE BLANCHE : \n         vous une bonne couleur au bon emplacement\n");
        rappel.setViewportView(jTextArea2);

        getContentPane().add(rappel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, 300, 110));

        setBounds(0, 0, 1032, 695);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        // TODO add your handling code here:
        rappel.setVisible(true);
        pannel_couleurs.setVisible(true);
        panneau_affichage.setVisible(true);
        initialiserPartie();
        annonce.setText("Le jeu commence: Séléctionnez une colonne");

        grilleJeu.repaint();
        btn_start.setEnabled(false);//pour ne pas que l'on recommence toujours une partie - désactive le bouton
    }//GEN-LAST:event_btn_startActionPerformed

    private void col_yellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col_yellowActionPerformed
        choixcoul(3);
        jButton.setIcon(obj2.img_yellow);
    }//GEN-LAST:event_col_yellowActionPerformed

    private void col_redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col_redActionPerformed

        choixcoul(0);
        jButton.setIcon(obj2.img_red);

    }//GEN-LAST:event_col_redActionPerformed

    private void col_greenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col_greenActionPerformed
        choixcoul(2);
        jButton.setIcon(obj2.img_green);
    }//GEN-LAST:event_col_greenActionPerformed

    private void col_pinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col_pinkActionPerformed
        choixcoul(1);
        jButton.setIcon(obj2.img_pink);
    }//GEN-LAST:event_col_pinkActionPerformed

    private void col_blueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col_blueActionPerformed
        choixcoul(5);
        jButton.setIcon(obj2.img_blue);
    }//GEN-LAST:event_col_blueActionPerformed

    private void col_orangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_col_orangeActionPerformed
        choixcoul(4);
        jButton.setIcon(obj2.img_orange);
    }//GEN-LAST:event_col_orangeActionPerformed

    private void jButton_45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_45ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(45, "attente d'une couleur");
        jButton = jButton_45;
    }//GEN-LAST:event_jButton_45ActionPerformed

    private void jButton_44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_44ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(44, "attente d'une couleur");
        jButton = jButton_44;
    }//GEN-LAST:event_jButton_44ActionPerformed

    private void jButton_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_0ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(0, "attente d'une couleur");
        jButton = jButton_0;
    }//GEN-LAST:event_jButton_0ActionPerformed

    private void jButton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(1, "attente d'une couleur");
        jButton = jButton_1;
    }//GEN-LAST:event_jButton_1ActionPerformed

    private void jButton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(2, "attente d'une couleur");
        jButton = jButton_2;
    }//GEN-LAST:event_jButton_2ActionPerformed

    private void jButton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_3ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(3, "attente d'une couleur");
        jButton = jButton_3;
    }//GEN-LAST:event_jButton_3ActionPerformed

    private void jButton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_4ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(4, "attente d'une couleur");
        jButton = jButton_4;
    }//GEN-LAST:event_jButton_4ActionPerformed

    private void jButton_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_5ActionPerformed
         annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(5, "attente d'une couleur");
        jButton = jButton_5;
    }//GEN-LAST:event_jButton_5ActionPerformed

    private void jButton_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_6ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(6, "attente d'une couleur");
        jButton = jButton_6;
    }//GEN-LAST:event_jButton_6ActionPerformed

    private void jButton_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_7ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(7, "attente d'une couleur");
        jButton = jButton_7;
    }//GEN-LAST:event_jButton_7ActionPerformed

    private void jButton_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_8ActionPerformed
                annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(8, "attente d'une couleur");
        jButton = jButton_8;

    }//GEN-LAST:event_jButton_8ActionPerformed

    private void jButton_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_9ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(9, "attente d'une couleur");
        jButton = jButton_9;
    }//GEN-LAST:event_jButton_9ActionPerformed

    private void jButton_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_10ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(10, "attente d'une couleur");
        jButton = jButton_10;
    }//GEN-LAST:event_jButton_10ActionPerformed

    private void jButton_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_11ActionPerformed
          annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(11, "attente d'une couleur");
        jButton = jButton_11;
    }//GEN-LAST:event_jButton_11ActionPerformed

    private void jButton_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_12ActionPerformed
         annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(12, "attente d'une couleur");
        jButton = jButton_12;
    }//GEN-LAST:event_jButton_12ActionPerformed

    private void jButton_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_13ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(13, "attente d'une couleur");
        jButton = jButton_13;
    }//GEN-LAST:event_jButton_13ActionPerformed

    private void jButton_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_14ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(14, "attente d'une couleur");
        jButton = jButton_14;
    }//GEN-LAST:event_jButton_14ActionPerformed

    private void jButton_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_15ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(15, "attente d'une couleur");
        jButton = jButton_15;
    }//GEN-LAST:event_jButton_15ActionPerformed

    private void jButton_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_16ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(16, "attente d'une couleur");
        jButton = jButton_16;
    }//GEN-LAST:event_jButton_16ActionPerformed

    private void jButton_17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_17ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(17, "attente d'une couleur");
        jButton = jButton_17;
    }//GEN-LAST:event_jButton_17ActionPerformed

    private void jButton_18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_18ActionPerformed
         annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(18, "attente d'une couleur");
        jButton = jButton_18;
    }//GEN-LAST:event_jButton_18ActionPerformed

    private void jButton_19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_19ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(19, "attente d'une couleur");
        jButton = jButton_19;

    }//GEN-LAST:event_jButton_19ActionPerformed

    private void jButton_20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_20ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(20, "attente d'une couleur");
        jButton = jButton_20;
    }//GEN-LAST:event_jButton_20ActionPerformed

    private void jButton_21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_21ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(21, "attente d'une couleur");
        jButton = jButton_21;
    }//GEN-LAST:event_jButton_21ActionPerformed

    private void jButton_22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_22ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(22, "attente d'une couleur");
        jButton = jButton_22;
    }//GEN-LAST:event_jButton_22ActionPerformed

    private void jButton_23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_23ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(23, "attente d'une couleur");
        jButton = jButton_23;
    }//GEN-LAST:event_jButton_23ActionPerformed

    private void jButton_24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_24ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(24, "attente d'une couleur");
        jButton = jButton_24;
    }//GEN-LAST:event_jButton_24ActionPerformed

    private void jButton_25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_25ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(25, "attente d'une couleur");
        jButton = jButton_25;
    }//GEN-LAST:event_jButton_25ActionPerformed

    private void jButton_26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_26ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(26, "attente d'une couleur");
        jButton = jButton_26;
    }//GEN-LAST:event_jButton_26ActionPerformed

    private void jButton_27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_27ActionPerformed
          annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(27, "attente d'une couleur");
        jButton = jButton_27;
    }//GEN-LAST:event_jButton_27ActionPerformed

    private void jButton_28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_28ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(28, "attente d'une couleur");
        jButton = jButton_28;
    }//GEN-LAST:event_jButton_28ActionPerformed

    private void jButton_29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_29ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(29, "attente d'une couleur");
        jButton = jButton_29;
    }//GEN-LAST:event_jButton_29ActionPerformed

    private void jButton_30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_30ActionPerformed
         annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(30, "attente d'une couleur");
        jButton = jButton_30;
    }//GEN-LAST:event_jButton_30ActionPerformed

    private void jButton_31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_31ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(31, "attente d'une couleur");
        jButton = jButton_31;
    }//GEN-LAST:event_jButton_31ActionPerformed

    private void jButton_32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_32ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(32, "attente d'une couleur");
        jButton = jButton_32;
    }//GEN-LAST:event_jButton_32ActionPerformed

    private void jButton_33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_33ActionPerformed
         annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(33, "attente d'une couleur");
        jButton = jButton_33;
    }//GEN-LAST:event_jButton_33ActionPerformed

    private void jButton_34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_34ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(34, "attente d'une couleur");
        jButton = jButton_34;
    }//GEN-LAST:event_jButton_34ActionPerformed

    private void jButton_35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_35ActionPerformed
       annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(35, "attente d'une couleur");
        jButton = jButton_35;
    }//GEN-LAST:event_jButton_35ActionPerformed

    private void jButton_36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_36ActionPerformed
       annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(36, "attente d'une couleur");
        jButton = jButton_36;

    }//GEN-LAST:event_jButton_36ActionPerformed

    private void jButton_37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_37ActionPerformed
         annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(37, "attente d'une couleur");
        jButton = jButton_37;
    }//GEN-LAST:event_jButton_37ActionPerformed

    private void jButton_38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_38ActionPerformed
       annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(38, "attente d'une couleur");
        jButton = jButton_38;
    }//GEN-LAST:event_jButton_38ActionPerformed

    private void jButton_39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_39ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(39, "attente d'une couleur");
        jButton = jButton_39;
    }//GEN-LAST:event_jButton_39ActionPerformed

    private void jButton_40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_40ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(40, "attente d'une couleur");
        jButton = jButton_40;
    }//GEN-LAST:event_jButton_40ActionPerformed

    private void jButton_41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_41ActionPerformed
         annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(41, "attente d'une couleur");
        jButton = jButton_41;
    }//GEN-LAST:event_jButton_41ActionPerformed

    private void jButton_42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_42ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(42, "attente d'une couleur");
        jButton = jButton_42;
    }//GEN-LAST:event_jButton_42ActionPerformed

    private void jButton_43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_43ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(43, "attente d'une couleur");
        jButton = jButton_43;
    }//GEN-LAST:event_jButton_43ActionPerformed

    private void jButton_46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_46ActionPerformed
          annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(46, "attente d'une couleur");
        jButton = jButton_46;
    }//GEN-LAST:event_jButton_46ActionPerformed

    private void jButton_47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_47ActionPerformed
        annonce.setText("Séléctionnez une couleur");
        Jeu_Joueur.set(47, "attente d'une couleur");
        jButton = jButton_47;
    }//GEN-LAST:event_jButton_47ActionPerformed

    public int placerDansColonne(int col) {
        colonne = col - 1;
        int indplacement = ligneEncours() * 4 + colonne;
        //activeButton_coul();
        return indplacement;
    }

    public int ligneEncours() {
        ligne += 1;
        return ligne;
    }

    public void activeButton_coul() {
        col_red.setEnabled(true);
        col_yellow.setEnabled(true);
        col_pink.setEnabled(true);
        col_blue.setEnabled(true);
        col_orange.setEnabled(true);
        col_green.setEnabled(true);

    }

    public void desactiveButton_coul() {
        col_red.setEnabled(false);
        col_yellow.setEnabled(false);
        col_pink.setEnabled(false);
        col_blue.setEnabled(false);
        col_orange.setEnabled(false);
        col_green.setEnabled(false);

    }

    /*
    public int avanc(){
        ind+=1;
        return ind;
    }
     */
    public void choixcoul(int indcoul) {
        //desactiveButton_coul();
        compteurcoul += 1;
        //int ind=Jeu_Joueur.indexOf("Attente de couleur");
        //int i=avanc();

        int index = Jeu_Joueur.indexOf("attente d'une couleur");
        Jeu_Joueur.set(index, obj1.creation_Jeu_Joueur(indcoul));

        System.out.println(Jeu_Joueur);

        //affichageGraph();
        if (compteurcoul == 4) {
            compteurcoul = 0;
            obj1.analyse_Jeu_Joueur(ligneEncours());
            //for (int i = 0; i < 4; i++) {
                //if (cellGraph.Pions==1) {
                    
                   /// grilleAnalyse.repaint();
                //} else if (obj1.Indice.get(i) == 0) {

                    //grilleAnalyse.repaint();
                //}
            }
            /*
            if (obj1.analyse_Jeu_Joueur(ligneEncours()) == true) {
                grilleJeu.setVisible(false);
                grilleAnalyse.setVisible(false);
                annonce.setText("Vous avez gagné!!!");
            }
            if (Jeu_Joueur.size() == 4) {

                grilleJeu.setVisible(false);
                grilleAnalyse.setVisible(false);
                annonce.setText("Vous avez perdu!!!");

            }
             */
        
        //annonce.setText("Séléctionnez une colonne");

        grilleJeu.repaint();

    }

    public void initialiserPartie() {
        obj1.combinaisonaléatoire();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetre_de_jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetre_de_jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetre_de_jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetre_de_jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetre_de_jeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea annonce;
    private javax.swing.JButton btn_start;
    private javax.swing.JButton col_blue;
    private javax.swing.JButton col_green;
    private javax.swing.JButton col_orange;
    private javax.swing.JButton col_pink;
    private javax.swing.JButton col_red;
    private javax.swing.JButton col_yellow;
    private javax.swing.JPanel grilleAnalyse;
    private javax.swing.JPanel grilleJeu;
    private javax.swing.JButton jButton_0;
    private javax.swing.JButton jButton_1;
    private javax.swing.JButton jButton_10;
    private javax.swing.JButton jButton_11;
    private javax.swing.JButton jButton_12;
    private javax.swing.JButton jButton_13;
    private javax.swing.JButton jButton_14;
    private javax.swing.JButton jButton_15;
    private javax.swing.JButton jButton_16;
    private javax.swing.JButton jButton_17;
    private javax.swing.JButton jButton_18;
    private javax.swing.JButton jButton_19;
    private javax.swing.JButton jButton_2;
    private javax.swing.JButton jButton_20;
    private javax.swing.JButton jButton_21;
    private javax.swing.JButton jButton_22;
    private javax.swing.JButton jButton_23;
    private javax.swing.JButton jButton_24;
    private javax.swing.JButton jButton_25;
    private javax.swing.JButton jButton_26;
    private javax.swing.JButton jButton_27;
    private javax.swing.JButton jButton_28;
    private javax.swing.JButton jButton_29;
    private javax.swing.JButton jButton_3;
    private javax.swing.JButton jButton_30;
    private javax.swing.JButton jButton_31;
    private javax.swing.JButton jButton_32;
    private javax.swing.JButton jButton_33;
    private javax.swing.JButton jButton_34;
    private javax.swing.JButton jButton_35;
    private javax.swing.JButton jButton_36;
    private javax.swing.JButton jButton_37;
    private javax.swing.JButton jButton_38;
    private javax.swing.JButton jButton_39;
    private javax.swing.JButton jButton_4;
    private javax.swing.JButton jButton_40;
    private javax.swing.JButton jButton_41;
    private javax.swing.JButton jButton_42;
    private javax.swing.JButton jButton_43;
    private javax.swing.JButton jButton_44;
    private javax.swing.JButton jButton_45;
    private javax.swing.JButton jButton_46;
    private javax.swing.JButton jButton_47;
    private javax.swing.JButton jButton_5;
    private javax.swing.JButton jButton_6;
    private javax.swing.JButton jButton_7;
    private javax.swing.JButton jButton_8;
    private javax.swing.JButton jButton_9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel panneau_affichage;
    private javax.swing.JPanel panneau_jeu;
    private javax.swing.JPanel pannel_couleurs;
    private javax.swing.JScrollPane rappel;
    // End of variables declaration//GEN-END:variables
}
